version: "3"
services:
  elasticsearch:
    build: ./elasticsearch
    environment:
      - node.name=es01
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 127.0.0.1:9200:9200

  # https://github.com/elastic/logstash-docker/blob/master/templates/docker-compose.yml.j2
  logstash:
    image: logstash:7.12.1
    volumes:
      - "./logstash/pipeline/:/usr/share/logstash/pipeline/"
      
