version: "3"
services:
  elasticsearch:
    build: ./elasticsearch
    environment:
      - node.name=es01
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 127.0.0.1:9200:9200

  # https://github.com/elastic/logstash-docker/blob/master/templates/docker-compose.yml.j2
  logstash:
    image: logstash:7.12.1
    volumes:
      - ./logstash/pipeline/:/usr/share/logstash/pipeline
      - ./logstash/jars/mysql-connector-java-8.0.24.jar:/usr/share/logstash/mysql-connector-java-8.0.24.jar
    environment:
      - XPACK_MONITORING_ENABLED=false
      
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_database
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --port 3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/sql:/docker-entrypoint-initdb.d
    ports:
      - "127.0.0.1:3306:3306"
